@TaskMasterAPI_HostAddress = http://localhost:5179


Accept: application/json

### obtener tareas
GET {{TaskMasterAPI_HostAddress}}/api/task/
Accept: application/json

### obtener tarea por id
GET {{TaskMasterAPI_HostAddress}}/api/task/4
Accept: application/json

### crear tarea
POST {{TaskMasterAPI_HostAddress}}/api/task/
Accept: application/json
Content-Type: application/json

{
  "title": "Crear una tarea",
  "description": "Crea una tarea usando el metodo POST"
}
